#pragma once

// NOLINTNEXTLINE
#define RENDERER_VERSION_MAJOR 0
// NOLINTNEXTLINE
#define RENDERER_VERSION_MINOR 1
// NOLINTNEXTLINE
#define RENDERER_VERSION_PATCH 0
// NOLINTNEXTLINE
#define RENDERER_VERSION                                                       \
  RENDERER_VERSION_MAJOR * 10000 + RENDERER_VERSION_MINOR * 100 +              \
      RENDERER_VERSION_PATCH
