macro(set_or_default var value default)
  if("${value}" STREQUAL "")
    set(${var} ${default})
  else()
    set(${var} ${value})
  endif()
endmacro()

macro(set_if_true var truthy value)
  if(${truthy})
    set(${var} ${value})
  else()
    set(${var} "")
  endif()
endmacro()

macro(set_once var value error_message)
  if(NOT DEFINED ${var})
    set(${var} ${value})
  else()
    if(NOT error_message STREQUAL "")
      message(FATAL_ERROR "${error_message}")
    else()
      message(FATAL_ERROR "Variable ${var} already set.")
    endif()
  endif()
endmacro()
